
# Use root/example as user/password credentials

services:

  db:
    container_name: mariabd-frank-11.8.1-noble-rc
    image: mariadb:11.8.1-noble-rc
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - "3308:3306"

  adminer:
    container_name: adminer-frank-5.3.0-standalone
    image: adminer:5.3.0-standalone
    restart: always
    ports:
      - "9080:8080"

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '9081:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '9025:25'
      # Change the number before : to the port the IMAP server should be accessible on
      #- '143:143'

